# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Data source for latest Amazon Linux 2 AMI in Tokyo
data "aws_ami" "amazon_linux_tokyo" {
  provider    = aws.tokyo
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-hvm-*-x86_64-gp2"]
  }
}

# Data source for latest Amazon Linux 2 AMI in Taipei
data "aws_ami" "amazon_linux_taipei" {
  provider    = aws.taipei
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-hvm-*-x86_64-gp2"]
  }
}
