# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "ap-northeast-1" # 東京
  alias  = "tokyo"
}

provider "aws" {
  region = "ap-northeast-3" # 台北
  alias  = "taipei"
}
